logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error

cloud:
  aws:
    stack:
      auto: false
    credentials:
      accessKey: test
      secret-key: test
      instance-profile: false
    region:
      static: us-east-1
      auto: false
      use-default-aws-region-chain: true

localstack:
  sqs:
    url: http://localhost:4566